language: r
sudo: false
cache: packages

before_install:
  - mkdir -p ~/.R
  - echo 'CXX17 = g++-7 -std=gnu++17 -fPIC' > ~/.R/Makevars

r:
  - release

os:
  - linux

warnings_are_errors: false

addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev
      - g++-7

r_packages:
  - covr
  - ggplot2
  - httr
  - jsonlite
  - stringr
  - text
  - tidytext
  - tidyverse
  - dplyr
  - tm
  - udpipe
  - wordcloud2

after_success:
  - Rscript -e 'library(covr); codecov()'



