---
title: "get_Word_Frequency"
output: html_document
date: "2024-01-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```


```{r}
library(httr)
library(jsonlite)
library(tidyverse)
library(tm)
library(wordcloud2)

client_id <- "JL7d1_eeiz7zeNLDwgEF5A"
client_secret <- "XUJEFa86M5-wWMXkhHRNFOhMODv0UQ"
user_agent <- "R:reddit_script:v1.0 (by /u/appleontree1990)"

response <- POST("https://www.reddit.com/api/v1/access_token",
                 authenticate(client_id, client_secret),
                 user_agent(user_agent),
                 body = list(grant_type = "client_credentials"),
                 encode = "form")

stop_for_status(response)
content <- httr::content(response)
if (response$status_code == 200) {
  access_token <- content$access_token
} else {
  stop("Request failed")
}

```

```{r}
#print(access_token)
```

```{r}

params <- list(
  context = 10,
  show = 'given',
  sort = 'new',
  t = 'day',
  type = 'comments',
  username = 'Crezarius',  # Replace with the actual username
  before = NULL,
  count = 25,
  limit = 100,
  sr_detail = TRUE,
  Authorization = access_token
)

# Send the GET request
url <- paste0("https://www.reddit.com/user/", params$username, "/comments.json")
response <- GET(url, query = params)

# Check the status of the response
print(status_code(response))

# If you need to work with data frames:
content_df <- httr::content(response, as = "text") %>% jsonlite::fromJSON(flatten = TRUE)
content_df[2]$data$children$data.body
vector <- content_df[2]$data$children$data.body

# Create a corpus from the vector
corpus <- Corpus(VectorSource(vector))

# Preprocess the corpus: remove punctuation, numbers, lowercase, strip whitespace, remove stopwords
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, stripWhitespace)
corpus <- tm_map(corpus, removeWords, stopwords("en"))

# Create a document-term matrix
dtm <- TermDocumentMatrix(corpus)

# Convert the document-term matrix to a matrix
m <- as.matrix(dtm)

# Calculate word frequencies
word_freqs <- sort(rowSums(m), decreasing = TRUE)

# Make a data frame for the word cloud
df_word_freqs <- data.frame(word=names(word_freqs), freq=word_freqs)

# Generate the word cloud
wordcloud2(df_word_freqs)
```
```{r}
content_df[2]$data$children$data.body
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
